Hw04 auth
Rom-dev-tech/nodejs-homework-rest-api pull request #3
Opened 2021-11-18 13:32 UTC by Rom-dev-tech

2021-11-18 13:35 UTC, Rom-dev-tech commented
Hello, check please my work :)

2021-11-20 19:32 UTC, KirillKulakow commented on controllers/contacts/getContactById.js
> +  if (!result || email !== result.owner.email) {
не вижу смысл в данной проверке по имейлу
а если в этом приложении появится обновление где юзер сможет менять свой имейл?)

2021-11-20 19:38 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +  const { page, limit = 20, favorite } = req.query
в тз нет но лучше здесь сделать проверку параметров приходящих с query
если page не число или лимит не число выдать badRequest
+ я не пойму как ты принимаешь поле favorite - так как все что приходит в query это строка

2021-11-20 19:39 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +    findBy.favorite = favorite
сюда передаешь тоже строку при том что favorite в схеме Mongoose это буль

2021-11-20 19:41 UTC, KirillKulakow commented on middlewares/authenticateContact.js
> +const { Contact } = require('../models')
ээээ... этот файл лишний, зачем делать проверку если все нужные проверки делает middleware/authenticate

2021-11-20 19:43 UTC, KirillKulakow commented on controllers/contacts/removeContact.js
> +  const validateUser = await authenticateContact(contactId, email)
зачем эта проверка?

2021-11-20 19:43 UTC, KirillKulakow commented on controllers/contacts/removeContact.js
> +  const validateUser = await authenticateContact(contactId, email)
считаю ее лишней

2021-11-20 19:43 UTC, KirillKulakow commented on controllers/contacts/removeContact.js
> +  const validateUser = await authenticateContact(contactId, email)
прошлый вариант был нормальным для данной ситуации

2021-11-20 19:44 UTC, KirillKulakow commented on controllers/contacts/updateContact.js
> +  const validateUser = await authenticateContact(contactId, email)
то же самое что и с удалением

2021-11-20 19:44 UTC, KirillKulakow commented on controllers/contacts/updateStatusContact.js
> +  const validateUser = await authenticateContact(contactId, email)
тоже самое что и с удалением

2021-11-20 19:45 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
при запросе списка контактов будучи не залогиненым приложение сломается в этом месте

2021-11-20 19:50 UTC, KirillKulakow commented on utils/httpErrors.js
> +const { NotFound, BadRequest, Conflict, Unauthorized } = require('http-errors')
дело твое но создавать отдельный файл ради 4 функций, внутри которых 1 строка - это странно
можешь оставить, но я бы так не делал
разработчик должен уметь сделать код как можно компактней, но при этом читаемый

2021-11-20 19:51 UTC, KirillKulakow requested changes
Need fix

2021-11-20 22:30 UTC, Rom-dev-tech commented on controllers/contacts/getContactById.js
> +  if (!result || email !== result.owner.email) {
Эта проверка для того, что бы данный Юзер не мог изменить, запросит либо удалить контакт, другого юзера по id. У меня сейчас два зарегистрированных пользователя(owner) с id 61963bd33094578ffdb6c7ce и 6196481743f9c127432498cd. Без этой проверки, узнав id другого юзера, я могу с ним работать... Это как то не правильно) В теории, может ведь такое случится? Если есть какой-то другой способ, как это реализвать, буду благодарен!

2021-11-22 09:57 UTC, Rom-dev-tech commented on controllers/contacts/getContactById.js
> +  if (!result || email !== result.owner.email) {
Уже разобрался и поправил)

2021-11-22 10:35 UTC, Rom-dev-tech commented on controllers/contacts/getContactById.js
> +  if (!result || email !== result.owner.email) {
Будем проверять по _id юзера, он я думаю будет не изменным)

2021-11-22 12:14 UTC, Rom-dev-tech commented on controllers/contacts/listContacts.js
> +  const { page, limit = 20, favorite } = req.query
Добавил проверку. 

"я не пойму как ты принимаешь поле favorite - так как все что приходит в query это строка" - не понял вопрос?

2021-11-22 12:15 UTC, Rom-dev-tech commented on controllers/contacts/listContacts.js
> +    findBy.favorite = favorite
Работает) Подскажи как сделать более грамотней?)

2021-11-22 12:26 UTC, Rom-dev-tech commented on middlewares/authenticateContact.js
> +const { Contact } = require('../models')
Я вынес эту функцию в отдельный middleware, что бы проверять является ли найденый контакт, юзера который его запрашивает, что бы было невозможно достучаться до чужих контактов. Описал выше. Функцию убрал, проверку сделал в самих методах по id пользователя)

2021-11-22 12:27 UTC, Rom-dev-tech commented on controllers/contacts/removeContact.js
> +  const validateUser = await authenticateContact(contactId, email)
Ответил ранее. Поправил.

2021-11-22 12:27 UTC, Rom-dev-tech commented on controllers/contacts/updateContact.js
> +  const validateUser = await authenticateContact(contactId, email)
Ответил ранее. Поправил.

2021-11-22 12:27 UTC, Rom-dev-tech commented on controllers/contacts/updateStatusContact.js
> +  const validateUser = await authenticateContact(contactId, email)
Ответил ранее. Поправил.

2021-11-22 12:28 UTC, Rom-dev-tech commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
Поправил, спасибо.

2021-11-22 12:30 UTC, Rom-dev-tech commented on utils/httpErrors.js
> +const { NotFound, BadRequest, Conflict, Unauthorized } = require('http-errors')
Нам говорили, что лучше выносить повторяющийся код, по этому и вынес) Так как и проверку в методах update delete указаных выше(authenticateContact). Убрал и всё поправил. Спасибо

2021-11-22 12:31 UTC, Rom-dev-tech commented on controllers/contacts/listContacts.js
> +  const { page, limit = 20, favorite } = req.query
Мне favorite нужен для запроса GET /contacts?favorite=true. От куда мне его взять?)

2021-11-22 12:55 UTC, Rom-dev-tech commented
Fixed check please)

2021-11-22 20:05 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +    findBy.favorite = favorite
как говорится - охрана отмена

2021-11-22 20:10 UTC, KirillKulakow commented on utils/httpErrors.js
> +const { NotFound, BadRequest, Conflict, Unauthorized } = require('http-errors')
ну хорошо - простая математика
здесь у тебя под каждую функцию выделено +/- 3 строки
там где ты ее вызываешь ты занимаешь одну строку

если бы у тебя этого файла не было - ты бы все равно занимал бы одну строку

Итог - у тебя лишний файл

Вот если бы в функциях было бы как минимум по 5 строк кода - тогда окей

2021-11-22 20:12 UTC, KirillKulakow commented on controllers/contacts/getContactById.js
> +  if (!result || String(_id) !== String(result.owner._id)) {
всю эту логику можно сделать проще
можно делать поиск не чисто по ид контакта но и с учетом ид обладателя сия контакта

можно применить и в остальных методах

2021-11-22 20:14 UTC, KirillKulakow requested changes
Need some fixes

2021-11-22 20:17 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +  const { page, limit = 20, favorite } = req.query
отменяю - но имею ввиду что не у всех бд есть схемы которые будут преобразовывать типы
в данной ситуации - если ты пишешь ?favorite=true , тебе приходит строка "true" и Mongoose преобразовывает эту строку в буль при поиске (исходя из типа прописанного в схеме)
пишу чтобы понимал важность проверки входящих параметров

2021-11-22 21:17 UTC, Rom-dev-tech commented on controllers/contacts/listContacts.js
> +  const { page, limit = 20, favorite } = req.query
К сожалению преподаватель не ставит акцент на проверку входящих данных, да и в общем на проверки... Я понимаю , что это важно и это умение прийдёт наверно только с опытом) Я тебе благодарен, если ты будешь поправлять в таком духе и давать дельные советы) Я так понимаю на favorite нужна проверка?

2021-11-22 21:18 UTC, Rom-dev-tech commented on utils/httpErrors.js
> +const { NotFound, BadRequest, Conflict, Unauthorized } = require('http-errors')
Это я понял и поправил. Спасибо

2021-11-22 21:51 UTC, Rom-dev-tech commented on controllers/contacts/getContactById.js
> +  if (!result || String(_id) !== String(result.owner._id)) {
Допёр))) Спасибо , что заставил меня подумать. Я понимал, что это должно делаться полегче, но видно не до конца!)) Пофиксил.

2021-11-22 21:53 UTC, Rom-dev-tech commented on controllers/contacts/listContacts.js
> +  const { page, limit = 20, favorite } = req.query
На данный момент Mongoose сам переводит из строки, посколько мы в схеме указали Type Boolean, верно я понял?)

2021-11-22 21:54 UTC, Rom-dev-tech commented
Fixed)

2021-11-23 18:55 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +  const { page, limit = 20, favorite } = req.query
Верно)

2021-11-23 18:57 UTC, KirillKulakow approved these changes

2021-11-23 19:07 UTC, merged