Hw05 avatars
Rom-dev-tech/nodejs-homework-rest-api pull request #4
Opened 2021-11-24 13:02 UTC by Rom-dev-tech

Check please :)

2021-11-24 20:04 UTC, KirillKulakow commented on controllers/auth/signup.js
> +  const avatar = gravatar.url(email)
здесь было бы неплохо добавить опцию протокола для корректной ссылки на аватара

2021-11-24 20:06 UTC, KirillKulakow commented on middlewares/upload.js
> +    const uniqueSuffix = file.fieldname + '-' + Math.round(Math.random() * 1e9)
было бы неплохо сделать проверку на MIME тип файла, чтобы файлы кроме изображений не загружались

2021-11-24 20:07 UTC, KirillKulakow requested changes
Need some fix

2021-11-25 10:05 UTC, Rom-dev-tech commented on controllers/auth/signup.js
> +  const avatar = gravatar.url(email)
Поправил, спасибо)

2021-11-25 10:26 UTC, Rom-dev-tech commented on middlewares/upload.js
> +    const uniqueSuffix = file.fieldname + '-' + Math.round(Math.random() * 1e9)
Тоже поправил, спасибо)

2021-11-25 20:04 UTC, KirillKulakow approved these changes

2021-11-25 20:47 UTC, merged